from paquete_1.modelo import *
garante = garante()
garante.agregarnombre("jason")
garante.agregarapellido("castillo")
garante.agregarsueldo(2500)
garante2 = garante()
garante2.agregarnombre("eduardo")
garante2.agregarapellido("riera")
garante2.agregarsueldo(1800)
prestamo = prestamo()
prestamo.agregargarante(g1)
prestamo.agregarnombrebeneficiario("pancho")
prestamo.agregarmontoprestamo(500)
prestamo.agregarinteres(3)
prestamo.agregartiempoprestamo(4)
prestamoauto = prestamoauto()
prestamoauto.agregargarante(g1)
prestamoauto.agregargarante2(g2)
prestamoauto.agregarnombrebeneficiario("marco")
prestamoauto.agregarmontoprestamo(500)
prestamoauto.agregarinteres(3)
prestamoauto.agregartiempoprestamo(4)
prestamoauto.agregartipovehiculo("camion")
prestamoauto.agregarmarcavehiculo("hino")

print(prestamo)
print(prestamoauto)